name = "recipe-view-worker"
main = "src/index.js"
compatibility_date = "2024-01-10"

# Development settings
[env.development]
name = "recipe-view-worker-dev"
vars = { ENVIRONMENT = "development", RECIPE_API_URL = "https://recipe-scraper-dev.recipesage2.workers.dev" }

# Staging settings
[env.staging]
name = "recipe-view-worker-staging"
vars = { ENVIRONMENT = "staging", RECIPE_API_URL = "https://recipe-scraper-staging.recipesage2.workers.dev" }

# Production settings (default)
vars = { ENVIRONMENT = "production", RECIPE_API_URL = "https://recipe-scraper.recipesage2.workers.dev" }