name = "recipe-view-worker"
main = "src/index.js"
compatibility_date = "2024-01-10"

# Development settings
[env.preview]
name = "preview-recipe-view-worker"

# Staging settings
[env.staging]
name = "staging-recipe-view-worker"

[observability]
enabled = true