name = "seasoned-frontend"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"
entry-point = "workers-site"

# For Cloudflare Pages, we use branch-based deployment
# Production branch (main) will use the default name
# Staging branch will create a preview deployment 