name = "seasoned-frontend"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
name = "seasoned-frontend-prod"

[env.staging]
name = "seasoned-frontend-staging" 