#!/bin/bash

echo "🔧 Manual Staging Resource Creation Commands"
echo "============================================="
echo ""
echo "Since wrangler requires authentication, please run these commands manually:"
echo ""

echo "1️⃣  CREATE STAGING D1 DATABASES:"
echo "================================"
echo ""
echo "# Create main recipe database for staging"
echo "wrangler d1 create recipe-db-staging"
echo ""
echo "# Create search database for staging" 
echo "wrangler d1 create recipe-search-db-staging"
echo ""

echo "2️⃣  CREATE STAGING R2 BUCKETS:"
echo "==============================="
echo ""
echo "# Create staging image bucket"
echo "wrangler r2 bucket create recipe-images-staging"
echo ""

echo "3️⃣  AFTER CREATION, UPDATE CONFIG FILES:"
echo "========================================"
echo ""
echo "The commands above will output database IDs like:"
echo '✅ Successfully created DB "recipe-db-staging" in region WEUR'
echo '  database_id = "abc123-def456-ghi789"'
echo ""
echo "Copy those database IDs and update these files:"
echo ""
echo "📝 clipped-recipe-db-worker/wrangler.toml:"
echo "   Replace: REPLACE_WITH_STAGING_DB_ID"
echo "   With: [the database_id from recipe-db-staging]"
echo ""
echo "📝 recipe-search-db/wrangler.toml:"
echo "   Replace: REPLACE_WITH_STAGING_SEARCH_DB_ID"
echo "   With: [the database_id from recipe-search-db-staging]"
echo ""

echo "4️⃣  RUN DATABASE MIGRATIONS:"
echo "============================"
echo ""
echo "# Migrate main recipe database"
echo "cd clipped-recipe-db-worker"
echo "wrangler d1 execute recipe-db-staging --file=schema.sql --env staging"
echo "cd .."
echo ""
echo "# Migrate search database"
echo "cd recipe-search-db"
echo "wrangler d1 execute recipe-search-db-staging --file=schema.sql --env staging"
echo "cd .."
echo ""

echo "5️⃣  VALIDATE CONFIGURATION:"
echo "==========================="
echo ""
echo "./validate-environments.sh"
echo ""

echo "6️⃣  DEPLOY TO STAGING:"
echo "====================="
echo ""
echo "./deploy-staging.sh"
echo ""

echo "📋 SUMMARY OF RESOURCES TO CREATE:"
echo "=================================="
echo "• recipe-db-staging (D1 database)"
echo "• recipe-search-db-staging (D1 database)"  
echo "• recipe-images-staging (R2 bucket)"
echo ""
echo "✅ KV namespace already configured: 3f8a3b17db9e4f8ea3eae83d864ad518"
echo ""
echo "🔒 This will complete the environment isolation and prevent data leakage!"