#!/bin/bash

echo "🔍 Recipe View Worker - Direct Test"
echo "==================================="
echo ""
echo "The recipe has been saved to the production KV storage."
echo ""
echo "Recipe ID: 65d7ae7464c81a23acb3339d4c018e61421c9a75851d237d5ef19b33693acb4a"
echo ""
echo "However, there's a configuration issue:"
echo "- The recipe was saved to: recipe-save-worker.nolanfoster.workers.dev"
echo "- But the view worker looks for recipes at: recipe-save-worker.recipesage2.workers.dev"
echo ""
echo "This is because of a hardcoded fallback URL in the view worker code (line 37):"
echo "  const apiUrl = env.RECIPE_SAVE_WORKER_URL || 'https://recipe-save-worker.recipesage2.workers.dev';"
echo ""
echo "To fix this, the view worker needs to be redeployed with the correct environment variable set,"
echo "or the fallback URL needs to be updated in the code."
echo ""
echo "For now, you can test the recipe view functionality locally by:"
echo "1. Running both workers locally"
echo "2. Using the test scripts provided"
echo ""
echo "The recipe data IS successfully saved and can be retrieved via:"
echo "curl https://recipe-save-worker.nolanfoster.workers.dev/recipe/get?id=65d7ae7464c81a23acb3339d4c018e61421c9a75851d237d5ef19b33693acb4a"