
name = "recipe-worker"
main = "src/index.js"
compatibility_date = "2024-08-09"

# Environment variables
[vars]
IMAGE_DOMAIN = "https://images.nolanfoster.me"

[env.preview]
name = "preview-clipped-recipe-db-worker"
[env.preview.vars]
IMAGE_DOMAIN = "https://preview-images.nolanfoster.me"

[env.staging]
name = "staging-clipped-recipe-db-worker"
[env.staging.vars]
IMAGE_DOMAIN = "https://staging-images.nolanfoster.me"

# Staging environment with separate database
[[env.staging.d1_databases]]
binding = "DB"
database_name = "recipe-db-staging"
database_id = "db352ab8-482f-4f5f-b134-07ecd8fb4b06"

[[env.staging.r2_buckets]]
binding = "recipe_images"
bucket_name = "recipe-images-staging"

# Production environment
[env.production]
name = "clipped-recipe-db-worker"
[env.production.vars]
IMAGE_DOMAIN = "https://images.nolanfoster.me"

[[env.production.d1_databases]]
binding = "DB"
database_name = "recipe-db"
database_id = "2b6e049b-bdfa-4291-be54-082c0d12146f"

[[env.production.r2_buckets]]
binding = "recipe_images"
bucket_name = "recipe-images"

[[d1_databases]]
binding = "DB"
database_name = "recipe-db"
database_id = "2b6e049b-bdfa-4291-be54-082c0d12146f"

[[r2_buckets]]
binding = "recipe_images"
bucket_name = "recipe-images"
