name = "recipe-worker-preview"
main = "src/index.js"
compatibility_date = "2024-08-09"

# Environment variables
[vars]
IMAGE_DOMAIN = "https://images.nolanfoster.me"

[[d1_databases]]
binding = "DB"
database_name = "recipe-db-preview"
database_id = "2b6e049b-bdfa-4291-be54-082c0d12146f"

[[r2_buckets]]
binding = "recipe_images"
bucket_name = "recipe-images-preview"