# Recipe Generation Worker Configuration
name = "recipe-generation-worker"
main = "src/index.js"
compatibility_date = "2024-01-10"

# Default configuration
[vars]
ENVIRONMENT = "development"

[observability]
enabled = true

# Preview environment (for PR previews)
[env.preview]
name = "recipe-generation-worker-preview"
[env.preview.vars]
ENVIRONMENT = "preview"

[env.preview.observability]
enabled = true

# Staging environment
[env.staging]
name = "recipe-generation-worker-staging"
[env.staging.vars]
ENVIRONMENT = "staging"

[env.staging.observability]
enabled = true

# Production environment
[env.production]
name = "recipe-generation-worker"
[env.production.vars]
ENVIRONMENT = "production"

[env.production.observability]
enabled = true