name = "recipe-generation-worker"
main = "src/index.js"
compatibility_date = "2024-01-10"

# Development settings
[env.preview]
name = "preview-recipe-generation-worker"
[env.preview.vars]
ENVIRONMENT = "preview"

[env.preview.observability]
enabled = true

# Staging settings
[env.staging]
name = "staging-recipe-generation-worker"
[env.staging.vars]
ENVIRONMENT = "staging"

[env.staging.observability]
enabled = true

# Production environment
[env.production]
name = "recipe-generation-worker-production"
[env.production.vars]
ENVIRONMENT = "production"

[env.production.observability]
enabled = true

[observability]
enabled = true