# recipe-app/wrangler.toml
name = "omni-recipe"
compatibility_date = "2025-03-07"
main = "src/worker.js"

[vars]
FLAGGLY_URL = "https://flaggly.nolanfoster.workers.dev"

[assets]
directory = "./dist"
