# Recipe Feeder Worker Configuration
name = "recipe-feeder"
main = "src/index.js"
compatibility_date = "2024-01-10"

# Default configuration
[vars]
ENVIRONMENT = "development"
BATCH_SIZE = "100"

[observability]
enabled = true

# Cron trigger - runs every hour
[triggers]
crons = ["0 * * * *"]

# Queue producer configuration for embedding queue
[[queues.producers]]
queue = "recipe-embedding-queue"
binding = "EMBEDDING_QUEUE"

# Preview environment (for PR previews)
[env.preview]
name = "recipe-feeder-preview"
[env.preview.vars]
ENVIRONMENT = "preview"
BATCH_SIZE = "50"

[env.preview.observability]
enabled = true

[env.preview.triggers]
crons = ["*/15 * * * *"]  # Every 15 minutes for testing

[[env.preview.kv_namespaces]]
binding = "RECIPE_STORAGE"
id = "3f8a3b17db9e4f8ea3eae83d864ad518"

[[env.preview.vectorize]]
binding = "RECIPE_VECTORS"
index_name = "recipe-vectors-384"

[[env.preview.queues.producers]]
queue = "recipe-embedding-queue"
binding = "EMBEDDING_QUEUE"

# Staging environment
[env.staging]
name = "recipe-feeder-staging"
[env.staging.vars]
ENVIRONMENT = "staging"
BATCH_SIZE = "75"

[env.staging.observability]
enabled = true

[env.staging.triggers]
crons = ["*/30 * * * *"]  # Every 30 minutes for staging

[[env.staging.kv_namespaces]]
binding = "RECIPE_STORAGE"
id = "3f8a3b17db9e4f8ea3eae83d864ad518"

[[env.staging.vectorize]]
binding = "RECIPE_VECTORS"
index_name = "recipe-vectors-384"

[[env.staging.queues.producers]]
queue = "recipe-embedding-queue"
binding = "EMBEDDING_QUEUE"

# Production environment
[env.production]
name = "recipe-feeder"
[env.production.vars]
ENVIRONMENT = "production"
BATCH_SIZE = "100"

[env.production.observability]
enabled = true

[env.production.triggers]
crons = ["0 * * * *"]  # Every hour in production

[[env.production.kv_namespaces]]
binding = "RECIPE_STORAGE"
id = "dd001c20659a4d6982f6d650abcac880"

[[env.production.vectorize]]
binding = "RECIPE_VECTORS"
index_name = "recipe-vectors-384"

[[env.production.queues.producers]]
queue = "recipe-embedding-queue"
binding = "EMBEDDING_QUEUE"