name = "auth-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV Namespace for OTP storage
[[kv_namespaces]]
binding = "OTP_KV"
id = "otp_kv_namespace_id" # Will be replaced with actual ID after creation

# Environment variables for external services
[vars]
USER_MANAGEMENT_WORKER_URL = "https://user-management-worker.your-domain.workers.dev"

# Observability settings
[observability]
enabled = true

# Preview environment (development)
[env.preview]
name = "auth-worker-preview"
vars = { 
  ENVIRONMENT = "preview",
  USER_MANAGEMENT_WORKER_URL = "https://user-management-worker-preview.your-domain.workers.dev"
}

[[env.preview.kv_namespaces]]
binding = "OTP_KV"
id = "otp_kv_namespace_preview_id" # Will be replaced with actual ID



[env.preview.observability]
enabled = true

# Production environment
[env.production]
name = "auth-worker-production"
vars = { 
  ENVIRONMENT = "production",
  USER_MANAGEMENT_WORKER_URL = "https://user-management-worker-production.your-domain.workers.dev"
}

[[env.production.kv_namespaces]]
binding = "OTP_KV"
id = "1fdebf1b59e249a691746f85a9eb5e62" # Will be replaced with actual ID



[env.production.observability]
enabled = true

# Staging environment
[env.staging]
name = "auth-worker-staging"
vars = { 
  ENVIRONMENT = "staging",
  USER_MANAGEMENT_WORKER_URL = "https://user-management-worker-staging.your-domain.workers.dev"
}

[[env.staging.kv_namespaces]]
binding = "OTP_KV"
id = "1fdebf1b59e249a691746f85a9eb5e62" # Will be replaced with actual ID



[env.staging.observability]
enabled = true