name = "auth-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV Namespace for OTP storage
[[kv_namespaces]]
binding = "OTP_KV"
id = "1fdebf1b59e249a691746f85a9eb5e62" # Will be replaced with actual ID after creation

# AWS SES environment variables
[vars]
AWS_REGION = "us-east-2"
FROM_EMAIL = "verify@seasonedapp.com"
USER_MANAGEMENT_WORKER_URL = "https://user-management-worker.nolanfoster.workers.dev"

# JWT configuration
# JWT_SECRET must be set as a Cloudflare secret using:
# wrangler secret put JWT_SECRET
# This should be a strong, random string of at least 32 characters

# Observability settings
[observability]
enabled = true

# Preview environment (development)
[env.preview]
name = "auth-worker-preview"

[[env.preview.kv_namespaces]]
binding = "OTP_KV"
id = "1fdebf1b59e249a691746f85a9eb5e62" # Will be replaced with actual ID

[env.preview.observability]
enabled = true

# Production environment
[env.production]
name = "auth-worker-production"

[env.production.vars]
AWS_REGION = "us-east-2"
FROM_EMAIL = "verify@seasonedapp.com"
USER_MANAGEMENT_WORKER_URL = "https://user-management-worker.nolanfoster.workers.dev"

[[env.production.kv_namespaces]]
binding = "OTP_KV"
id = "1fdebf1b59e249a691746f85a9eb5e62" # Will be replaced with actual ID

[env.production.observability]
enabled = true

# Staging environment
[env.staging]
name = "auth-worker-staging"

[env.staging.vars]
AWS_REGION = "us-east-2"
FROM_EMAIL = "verify@seasonedapp.com"
USER_MANAGEMENT_WORKER_URL = "https://user-management-worker.nolanfoster.workers.dev"

[[env.staging.kv_namespaces]]
binding = "OTP_KV"
id = "1fdebf1b59e249a691746f85a9eb5e62" # Will be replaced with actual ID

[env.staging.observability]
enabled = true
