name = "recipe-recommendation-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Enable observability features
[observability]
enabled = true

# AI binding for Cloudflare Workers AI
[ai]
binding = "AI"

# Analytics Engine binding for metrics collection
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "recipe_recommendations_metrics"

[env.production]
name = "recipe-recommendation-worker"
vars = { }

[env.production.ai]
binding = "AI"

[[env.production.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "recipe_recommendations_metrics_prod"

[env.preview]
name = "preview-recipe-recommendation-worker"
vars = { }

[env.preview.ai]
binding = "AI"

[[env.preview.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "recipe_recommendations_metrics_preview"

# Staging environment
[env.staging]
name = "staging-recipe-recommendation-worker"
vars = { }

[env.staging.ai]
binding = "AI"

[[env.staging.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "recipe_recommendations_metrics_staging"

# Note: With Cloudflare AI binding, you don't need OpenAI API keys
# The AI models are provided by Cloudflare Workers AI