name = "recipe-recommendation-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Enable observability features
[observability]
enabled = true

# AI binding for Cloudflare Workers AI
[ai]
binding = "AI"

# Analytics Engine binding for metrics collection
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "recipe_recommendations_metrics"

# Service binding to recipe search worker
[[services]]
binding = "SEARCH_WORKER"
service = "recipe-search-db"

# Environment variables for recipe integration
[vars]
SEARCH_DB_URL = "https://recipe-search-db.nolanfoster.workers.dev"
RECIPE_SAVE_WORKER_URL = "https://recipe-save-worker.nolanfoster.workers.dev"

[env.production]
name = "recipe-recommendation-worker"
[env.production.vars]
SEARCH_DB_URL = "https://recipe-search-db.nolanfoster.workers.dev"
RECIPE_SAVE_WORKER_URL = "https://recipe-save-worker.nolanfoster.workers.dev"


[env.production.ai]
binding = "AI"

[[env.production.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "recipe_recommendations_metrics_prod"

[[env.production.services]]
binding = "SEARCH_WORKER"
service = "recipe-search-db"

[env.preview]
name = "preview-recipe-recommendation-worker"
[env.preview.vars]
SEARCH_DB_URL = "https://recipe-search-db.nolanfoster.workers.dev"
RECIPE_SAVE_WORKER_URL = "https://recipe-save-worker.nolanfoster.workers.dev"


[env.preview.ai]
binding = "AI"

[[env.preview.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "recipe_recommendations_metrics_preview"

[[env.preview.services]]
binding = "SEARCH_WORKER"
service = "recipe-search-db"

# Staging environment
[env.staging]
name = "staging-recipe-recommendation-worker"
[env.staging.vars]
SEARCH_DB_URL = "https://staging-recipe-search-db.nolanfoster.workers.dev"
RECIPE_SAVE_WORKER_URL = "https://recipe-save-worker.nolanfoster.workers.dev"

[env.staging.ai]
binding = "AI"

[[env.staging.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "recipe_recommendations_metrics_staging"

[[env.staging.services]]
binding = "SEARCH_WORKER"
service = "staging-recipe-search-db"

# Note: With Cloudflare AI binding, you don't need OpenAI API keys
# The AI models are provided by Cloudflare Workers AI