name = "user-management-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 Databases
[[d1_databases]]
binding = "USER_DB"
database_name = "user-db"
database_id = "863a849b-1dd9-4832-a23b-977ff508713a"

# Observability settings
[observability]
enabled = true

# Preview environment (development)
[env.preview]
name = "user-management-worker-preview"
vars = { ENVIRONMENT = "preview" }

[[env.preview.d1_databases]]
binding = "USER_DB"
database_name = "user-db-preview"
database_id = "863a849b-1dd9-4832-a23b-977ff508713a"

[env.preview.observability]
enabled = true

# Production environment
[env.production]
name = "user-management-worker-production"
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "USER_DB"
database_name = "user-db-production"
database_id = "f8a952a5-acdb-48c7-88e7-57a53402e719"

[env.production.observability]
enabled = true

# Staging environment
[env.staging]
name = "user-management-worker-staging"
vars = { ENVIRONMENT = "staging" }

[[env.staging.d1_databases]]
binding = "USER_DB"
database_name = "user-db-staging"
database_id = "171ffc3f-40bd-4738-b879-4ccd8d79db39"

[env.staging.observability]
enabled = true
