name = "recipe-clipper-worker"
main = "src/recipe-clipper.js"
compatibility_date = "2024-08-09"

# AI binding for Cloudflare Workers AI
[ai]
binding = "AI"

# Environment variables
[vars]
GPT_API_URL = "https://api.openai.com/v1/chat/completions"
IMAGE_DOMAIN = "https://images.nolanfoster.me"

[env.preview]
name = "preview-clipper"

[env.preview.ai]
binding = "AI"

[env.staging]
name = "staging-clipper"
[env.staging.vars]
GPT_API_URL = "https://api.openai.com/v1/chat/completions"
IMAGE_DOMAIN = "https://staging-images.nolanfoster.me"

[env.staging.ai]
binding = "AI"

# Staging KV Namespaces for storing recipes
[[env.staging.kv_namespaces]]
binding = "RECIPE_STORAGE"
id = "dd001c20659a4d6982f6d650abcac880"

# Production environment
[env.production]
name = "clipper"
[env.production.vars]
GPT_API_URL = "https://api.openai.com/v1/chat/completions"
IMAGE_DOMAIN = "https://images.nolanfoster.me"

[env.production.ai]
binding = "AI"

[[env.production.kv_namespaces]]
binding = "RECIPE_STORAGE"
id = "dd001c20659a4d6982f6d650abcac880"

# KV Namespaces for storing recipes
[[kv_namespaces]]
binding = "RECIPE_STORAGE"
id = "dd001c20659a4d6982f6d650abcac880"
preview_id = "dd001c20659a4d6982f6d650abcac880"

[observability.logs]
enabled = true

# Secrets (to be set via wrangler secret put GPT_API_KEY)
# GPT_API_KEY will be set as a secret

# Optional: Add any additional bindings if needed
# [[d1_databases]]
# binding = "DB"
# database_name = "recipe-db"
# database_id = "2b6e049b-bdfa-4291-be54-082c0d12146f"