name = "recipe-clipper-worker-preview"
main = "src/recipe-clipper.js"
compatibility_date = "2024-08-09"

# AI binding for Cloudflare Workers AI
[ai]
binding = "AI"

# KV Namespaces for storing recipes (using preview_id)
[[kv_namespaces]]
binding = "RECIPE_STORAGE"
id = "dd001c20659a4d6982f6d650abcac880"
preview_id = "3f8a3b17db9e4f8ea3eae83d864ad518"

# Environment variables
[vars]
GPT_API_URL = "https://api.openai.com/v1/chat/completions"
IMAGE_DOMAIN = "https://images.nolanfoster.me"

[observability.logs]
enabled = true

# Secrets (to be set via wrangler secret put GPT_API_KEY)
# GPT_API_KEY will be set as a secret