name = "recipe-scraper"
main = "worker.js"
compatibility_date = "2024-01-01"

# Uncomment and set your account_id to deploy
# account_id = "your-account-id"

# Worker configuration
workers_dev = true

# Environment variables (if needed)
[vars]
# Add any environment variables here
IMAGE_DOMAIN = "https://images.nolanfoster.me"

[env.preview]
name = "preview-recipe-scraper"

# Routes (optional - for custom domains)
# [[routes]]
# pattern = "example.com/api/*"
# zone_id = "your-zone-id"

# KV Namespaces for storing recipes
[[kv_namespaces]]
binding = "RECIPE_STORAGE"
id = "dd001c20659a4d6982f6d650abcac880"
preview_id = "3f8a3b17db9e4f8ea3eae83d864ad518"

# Durable Objects (if you want persistent storage)
# [[durable_objects.bindings]]
# name = "RECIPE_STORAGE"
# class_name = "RecipeStorage"

# R2 Buckets (if you want to store recipe images)
[[r2_buckets]]
binding = "RECIPE_IMAGES"
bucket_name = "recipe-images"

[observability.logs]
enabled = true