name = "recipe-search-db-preview"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
# Add any environment variables here

# D1 Database for search graph (using preview database)
[[d1_databases]]
binding = "SEARCH_DB"
database_name = "recipe-search-db-preview"
database_id = "69a59404-ca73-4760-bb87-0ac910752ca9"

# KV Namespaces for recipe storage (using preview_id)
[[kv_namespaces]]
binding = "RECIPE_STORAGE"
id = "dd001c20659a4d6982f6d650abcac880"
preview_id = "3f8a3b17db9e4f8ea3eae83d864ad518"

[observability.logs]
enabled = true