name = "recipe-search-db"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
# Add any environment variables here

[env.preview]
name = "preview-recipe-search-db"

[env.staging]
name = "staging-recipe-search-db"

[env.staging.vars]
# Add any environment variables here

# Staging D1 Database for search graph
[[env.staging.d1_databases]]
binding = "SEARCH_DB"
database_name = "recipe-search-db"
database_id = "69a59404-ca73-4760-bb87-0ac910752ca9"

# Staging KV Namespaces for recipe storage
[[env.staging.kv_namespaces]]
binding = "RECIPE_STORAGE"
id = "3f8a3b17db9e4f8ea3eae83d864ad518"

# Production environment
[env.production]
name = "recipe-search-db"

[env.production.vars]
# Add any environment variables here

[[env.production.d1_databases]]
binding = "SEARCH_DB"
database_name = "recipe-search-db"
database_id = "69a59404-ca73-4760-bb87-0ac910752ca9"

[[env.production.kv_namespaces]]
binding = "RECIPE_STORAGE"
id = "dd001c20659a4d6982f6d650abcac880"

# D1 Database for search graph
[[d1_databases]]
binding = "SEARCH_DB"
database_name = "recipe-search-db"
database_id = "69a59404-ca73-4760-bb87-0ac910752ca9"

# R2 Buckets (if needed for storing search indexes)
# [[r2_buckets]]
# binding = "search_indexes"
# bucket_name = "recipe-search-indexes"

[observability.logs]
enabled = true
