name: Auth Worker Tests

on:
  push:
    branches: [ main, staging, develop ]
    paths:
      - 'auth-worker/**'
      - 'shared/**'
      - '.github/workflows/auth-worker-tests.yml'
  pull_request:
    branches: [ main, staging ]
    paths:
      - 'auth-worker/**'
      - 'shared/**'
      - '.github/workflows/auth-worker-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: auth-worker/package-lock.json
    
    - name: Install shared dependencies
      run: |
        cd shared
        npm ci
    
    - name: Install dependencies
      run: |
        cd auth-worker
        npm ci
    
    - name: Run linting
      run: |
        cd auth-worker
        npm run lint
    
    - name: Run type checking
      run: |
        cd auth-worker
        npm run type-check
    
    - name: Run tests with coverage
      run: |
        cd auth-worker
        npm run test:coverage
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./auth-worker/coverage/lcov.info
        flags: unittests
        name: auth-worker-coverage
        fail_ci_if_error: true
    
    - name: Check coverage thresholds
      run: |
        cd auth-worker
        coverage=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
        if (( $(echo "$coverage < 80" | bc -l) )); then
          echo "Coverage is below 80%"
          exit 1
        fi