name: Deploy Clipped Recipe DB Worker Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'clipped-recipe-db-worker/**'
      - '.github/workflows/deploy-preview-clipped-recipe-db.yml'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    name: Deploy Clipped Recipe DB Worker Preview
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        working-directory: ./clipped-recipe-db-worker
        run: npm ci
        
      - name: Deploy Preview to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: './clipped-recipe-db-worker'
          command: deploy --env preview
          
      - name: Create deployment comment
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const deploymentUrl = `https://preview.clipped-recipe-db-worker.${context.repo.owner}.workers.dev`;
            
            const comment = `🚀 **Clipped Recipe DB Worker Preview Deployed!**
            
            Preview URL: ${deploymentUrl}
            
            **Test endpoints:**
            - GET \`${deploymentUrl}/api/recipes\` - List recipes
            - GET \`${deploymentUrl}/api/recipes/:id\` - Get recipe by ID
            - POST \`${deploymentUrl}/api/recipes\` - Save recipe
            - DELETE \`${deploymentUrl}/api/recipes/:id\` - Delete recipe
            - GET \`${deploymentUrl}/api/recipes/user/:userId\` - Get user's recipes
            - GET \`${deploymentUrl}/api/health\` - Health check
            
            **Example request:**
            \`\`\`bash
            curl ${deploymentUrl}/api/health
            \`\`\`
            
            This preview will be automatically updated with each new commit.`;
            
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });