name: Shared Components Tests

on:
  push:
    branches: [ main, staging ]
    paths:
      - 'shared/**'
      - '.github/workflows/shared-tests.yml'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main, staging ]
    paths:
      - 'shared/**'
      - '.github/workflows/shared-tests.yml'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write

jobs:
  test-shared:
    name: Shared Components Tests
    runs-on: ubuntu-latest
    outputs:
      tests_passed: ${{ steps.test-results.outputs.tests_passed }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: shared/package-lock.json
    
    - name: Install Shared Dependencies
      working-directory: ./shared
      run: npm ci
    
    - name: Run Shared Tests
      id: test-results
      working-directory: ./shared
      run: |
        # Run tests if test script exists, otherwise skip
        if npm run | grep -q "test"; then
          if npm test; then
            echo "tests_passed=true" >> $GITHUB_OUTPUT
            echo "Tests passed successfully"
          else
            echo "tests_passed=false" >> $GITHUB_OUTPUT
            echo "No tests found or test script not configured"
            exit 1
          fi
        else
          echo "tests_passed=true" >> $GITHUB_OUTPUT
          echo "No test script found in package.json"
        fi
        
        # Note: Shared tests currently don't generate coverage reports
        # Consider adding coverage collection for shared tests in the future

  lint-shared:
    name: Shared Components Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Lint Shared Components
      working-directory: ./shared
      run: |
        npm ci
        if npm run | grep -q "lint"; then
          npm run lint || echo "Linting completed with warnings"
        else
          echo "No lint script found"
        fi

  # Slack notification for test failures
  notify-test-failure:
    name: Notify Slack on Test Failure
    needs: test-shared
    if: always() && needs.test-shared.outputs.tests_passed == 'false'
    uses: ./.github/workflows/slack-notify-cursor.yml
    with:
      test_type: 'unit-tests'
      workflow_name: 'Shared Components Tests'
      failure_details: 'Shared components unit tests failed'
      branch: ${{ github.ref_name }}
      commit_sha: ${{ github.sha }}
      run_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    secrets: inherit
