name: Generic Worker Tests (Deprecated)

on:
  push:
    branches: [ main, staging ]
    paths:
      - 'worker/**'
      - '.github/workflows/worker-tests.yml'
  pull_request:
    branches: [ main, staging ]
    paths:
      - 'worker/**'
      - '.github/workflows/worker-tests.yml'

jobs:
  deprecated-notice:
    name: Deprecated Workflow Notice
    runs-on: ubuntu-latest
    
    steps:
    - name: Workflow Deprecated
      run: |
        echo "This workflow is deprecated as there is no generic worker directory."
        echo "Worker-specific tests are handled in their respective workflows:"
        echo "- clipped-recipe-db-worker-tests.yml"
        echo "- recipe-recommendation-worker-tests.yml"
